import { StyleSheet, StatusBar } from 'react-native';


const styles = StyleSheet.create({
  //Pantalla inicio
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 15,
    top: 200,
    elevation: 8,
    backgroundColor: '#007bff',
    fontWeight: 'bold',
    fontFamily:'sans-serif',
    width: 300
  },
  button2: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 15,
    top: 240,
    elevation: 8,
    backgroundColor: '#007bff',
    fontWeight: 'bold',
    fontFamily:'sans-serif',
    width: 300
  },
  button3: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 15,
    top: 280,
    fontWeight: 'bold',
    fontFamily:'sans-serif',
    width: 300
  },
  text: {
    fontSize: 20,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
    fontFamily:'sans-serif'
  },
  textDatosProfesor: {
    textAlign: "justify",
    fontFamily: 'sans-serif',
    fontSize: 20,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },


  //Vista talleres
  containerVT: {
    flex: 1,
    backgroundColor: '#4054B2',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  item: {
    /*backgroundColor: '#0056b3',*/
    backgroundColor: '#17263f',
    padding: 10,
    borderRadius: 15,
    marginVertical: 8,
    marginHorizontal: 13,
    height: 410,
  },
  itemTittle: {
    backgroundColor: '#00a455',
    padding: 10,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    marginTop: 10,
    start: 0,
    marginBottom: 23,
  },
  item2: {
    backgroundColor: '#00a455',
    paddingBottom: 19,
    paddingTop: 19,
    marginHorizontal: 105,
    top: -291,
    start: 105,
  },
  item3: {
    backgroundColor: '#fba81a',
    paddingBottom: 19,
    paddingTop: 19,
    marginHorizontal: 105,
    marginTop: 10,
    top: -290,
    start: 105,
  },
  item4: {
    backgroundColor: '#0f75bc',
    paddingBottom: 4,
    paddingTop: 19,
    borderBottomRightRadius: 15,
    marginHorizontal: 105,
    top: -292,
    start: 105,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: 'center',
    color: 'white',
    fontFamily:'sans-serif'
  },
  modalidadTalleres: {
    fontSize: 20,
    textAlign: 'center',
    color: 'white',
    fontFamily:'sans-serif',
    top: -5,
  },
  text2: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
    textAlign: 'center',
    fontFamily:'sans-serif'
  },

  text3: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
    textAlign: 'center',
    fontFamily:'sans-serif',
    top: -5,
  },
  texto: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
    fontFamily: 'sans-serif',
  },
  texto2: {
    fontSize: 30,
    textAlign: 'justify',
    color: 'black',
    fontFamily: 'sans-serif',
  },

  buttonVT: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 50,
    borderRadius: 15,
    backgroundColor: '#0f75bc',
    top: -270,
    start: 55,
    width: 250,
  },

  //Vista Detalles taller
  contenedorImagen: {
    alignItems: 'center',
  },
  imagen: {
    alignItems: 'center',
    width: 350,
    height: 320,
    marginBottom: 15,
    borderRadius: 30,
    resizeMode: "contain",
    top: 10,
  },
  itemCupos: {
    backgroundColor: '#fba81a',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginHorizontal: 90,
    marginTop: 10,
    elevation: 8,
    top: -10,
    start: -90,

  },
  textSubsecciones: {
    fontSize: 20,
    lineHeight: 21,
    textAlign: 'justify',
    color: 'white',
    fontWeight: 'bold',
    fontFamily:'sans-serif',
    letterSpacing: 0.25,
  },

  itemEstadoActividad: {
    backgroundColor: '#00a455',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginHorizontal: 90,
    marginTop: 10,
    elevation: 8,
    top: -100,
    start: 90,
  },
  itemFechaInicio: {
    backgroundColor: '#00a455',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginHorizontal: 90,
    marginTop: 10,
    elevation: 8,
    top: -100,
    start: -90,
  },
  itemFechaTermino: {
    backgroundColor: '#fba81a',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginHorizontal: 90,
    marginTop: 10,
    elevation: 8,
    top: -192,
    start: 90,
  },
  titleFechaTermino: {
    fontSize: 18,
    fontWeight:"bold",
    textAlign: 'center',
    fontFamily:'sans-serif',
    color: 'white',
  },
  itemArea: {
    backgroundColor: '#fba81a',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginHorizontal: 90,
    marginTop: 10,
    elevation: 8,
    top: -190,
    start: -90,
  },
  itemModalidad: {
    backgroundColor: '#00a455',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginHorizontal: 90,
    marginTop: 10,
    elevation: 8,
    top: -282,
    start: 90,
  },

  itemVDT: {
    backgroundColor: '#0056b3',
    padding: 10,
    borderRadius: 15,
    marginVertical: 8,
    marginHorizontal: 13,
  },

  detalles1: {
    backgroundColor: '#17263f',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginTop: 10,
    elevation: 8,
    height: 290,
  },
  detalles2: {
    backgroundColor: '#17263f',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginTop: 10,
    elevation: 8,
  },
  datosprofesor: {
    backgroundColor: '#17263f',
    padding: 10,
    borderRadius: 15,
    marginVertical: 2,
    marginTop: 10,
    elevation: 8,
  },
  subseccion: {
    backgroundColor: '#00a455',
    padding: 5,
    borderRadius: 15,
    margin: 2,
  },
  buttonVDT: {
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    marginTop: 5,
    borderRadius: 15,
    backgroundColor: '#007bff',
  },
  correo: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },

  //Vista SIn Elementos
  itemVSE: {
    backgroundColor: '#0056b3',
    padding: 10,
    borderRadius: 15,
    marginVertical: 8,
    marginHorizontal: 13,
    height: 500,
  },
  buttonVSE: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 15,
    elevation: 8,
    backgroundColor: '#007bff',
    top: 40,
    start: 35,
    width: 300,
  },

  //VIsta Error
  itemError: {
    top: 100,
    backgroundColor: '#0056b3',
    padding: 10,
    borderRadius: 15,
    marginVertical: 8,
    marginHorizontal: 13,
    height: 500,
  },
  buttonError: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 15,
    elevation: 8,
    backgroundColor: '#007bff',
    top: 50,
    start: 35,
    width: 300,
  },
  imagenVSE: {
    start: 40,
    alignItems: 'center',
    width: 280,
    height: 270,
    marginBottom: 15,
    borderRadius: 30,
    resizeMode: "contain",
    top: 10,
  },
  hTitulos: {
    backgroundColor: '#3b8afd',
    start: 15,
    alignItems: 'center',
    width: 380,
    height: 55,
    marginBottom: 15,
    borderRadius: 15,
    resizeMode: "contain",
    top: 0,
  },

  hTituloPostulaciones: {
    backgroundColor: '#00a455',
    start: 15,
    alignItems: 'center',
    width: 380,
    marginBottom: 15,
    borderRadius: 15,
    resizeMode: "contain",
  },
  inputCamposRut: {
    paddingLeft:10,
    margin: 12,
    borderWidth: 1,
    padding: 0,
    width:50,
    alignItems: 'center',
    backgroundColor:'white',
    borderColor:'gray',
    borderRadius:10,
    flex:1
  },
  row: {
    flex: 1,
    flexDirection: "row"
  },
  textRut: {
    top:20,
    color: 'white',
  },
  buttonPostular: {
    start:30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 15,
    elevation: 8,
    backgroundColor: '#007bff',
    fontWeight: 'bold',
    width: 300
  },
  inputNombreCompleto: {
    margin: 12,
    paddingLeft:10,
    borderWidth: 1,
    width:"90%",
    alignItems: 'center',
    backgroundColor:'white',
    borderColor:'gray',
    borderRadius:10,
    flex:1
  },
  inputNumeroContacto: {
    paddingLeft:10,
    margin: 12,
    borderWidth: 1,
    width:50,
    paddingLeft:10,
    alignItems: 'center',
    backgroundColor:'white',
    borderColor:'gray',
    borderRadius:10,
    flex:0.8
  },
  inputCorreo: {
    margin: 12,
    borderWidth: 1,
    height:120,
    padding:10,
    width:"90%",
    alignItems: 'center',
    backgroundColor:'white',
    borderColor:'gray',
    borderRadius:10,
    flex:1
  },
  hSubseccionLocalidad: {
    backgroundColor: '#00a455',
    alignItems: 'center',
    width: "100%",
    marginBottom: 15,
    borderRadius: 15,
    resizeMode: "contain",
  },
  inputPoblacion: {
    margin: 12,
    borderWidth: 1,
    width:"90%",
    paddingLeft:10,
    alignItems: 'center',
    backgroundColor:'white',
    borderColor:'gray',
    borderRadius:10,
    flex:0.8
  },
  inputNumero: {
    margin: 12,
    borderWidth: 1,
    width:120,
    paddingLeft:10,
    alignItems: 'center',
    backgroundColor:'white',
    borderColor:'gray',
    borderRadius:10,
    flex:0.8
  },
 
});

export { styles };